<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE messages [
<!ELEMENT messages (message)*>
<!ELEMENT message (name , website? , comment , date , user_ip? , user_agent? , spam)>
<!ATTLIST message mID ID #REQUIRED>
<!ELEMENT name (#PCDATA)>
<!ELEMENT website (#PCDATA)>
<!ELEMENT comment (#PCDATA)>
<!ELEMENT date (#PCDATA)>
<!ELEMENT spam (#PCDATA)>
<!ELEMENT user_ip (#PCDATA)>
<!ELEMENT user_agent (#PCDATA)>
]>
<messages><message mID="m2480272dd56c880.19833969"><name>test</name><website/><comment>test'''</comment><date>1208120029</date><user_ip>127.0.0.1</user_ip><user_agent>Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.9b4) Gecko/2008030318 Firefox/3.0b4</user_agent><spam>1</spam></message><message mID="m5480273424921b9.05534013"><name>test</name><website/><comment>test''</comment><date>1208120130</date><user_ip>127.0.0.1</user_ip><user_agent>Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.9b4) Gecko/2008030318 Firefox/3.0b4</user_agent><spam>0</spam></message><message mID="m1480274041a5a60.19984510"><name>test</name><website/><comment>:'(</comment><date>1208120324</date><user_ip>127.0.0.1</user_ip><user_agent>Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.9b4) Gecko/2008030318 Firefox/3.0b4</user_agent><spam>0</spam></message><message mID="m2480274134f5d32.92666589"><name>test</name><website/><comment>test :'(</comment><date>1208120339</date><user_ip>127.0.0.1</user_ip><user_agent>Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.9b4) Gecko/2008030318 Firefox/3.0b4</user_agent><spam>1</spam></message><message mID="m448027446c04a74.22918490"><name>test</name><website/><comment>:'(</comment><date>1208120390</date><user_ip>127.0.0.1</user_ip><user_agent>Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.9b4) Gecko/2008030318 Firefox/3.0b4</user_agent><spam>0</spam></message><message mID="m5480291672ffd02.07927751"><name>test</name><website/><comment>test</comment><date>1208127847</date><user_ip>127.0.0.1</user_ip><user_agent>Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.9b4) Gecko/2008030318 Firefox/3.0b4</user_agent><spam>0</spam></message><message mID="m14802916d4e7c31.34696868"><name>hi</name><website></website><comment>:)</comment><date>1208127853</date><user_ip>127.0.0.1</user_ip><user_agent>Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.9b4) Gecko/2008030318 Firefox/3.0b4</user_agent><spam>0</spam></message></messages>
