<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE messages [
<!ELEMENT messages (message)*>
<!ELEMENT message (name , website? , comment , date , user_ip? , user_agent? , spam)>
<!ATTLIST message mID ID #REQUIRED>
<!ELEMENT name (#PCDATA)>
<!ELEMENT website (#PCDATA)>
<!ELEMENT comment (#PCDATA)>
<!ELEMENT date (#PCDATA)>
<!ELEMENT spam (#PCDATA)>
<!ELEMENT user_ip (#PCDATA)>
<!ELEMENT user_agent (#PCDATA)>
]>
<messages>
<message mID="m54869eb5869a912.15103283"><name>1</name><website/><comment>1</comment><date>1214901080</date><user_ip>194.123.133.241</user_ip><user_agent>Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_4_11; nl-nl) AppleWebKit/525.18 (KHTML, like Gecko) Version/3.1.1 Safari/525.18</user_agent><spam>0</spam></message><message mID="m24869ec8ea92725.65540812"><name>Toto</name><website>http://www.toto.com</website><comment>Test</comment><date>1214901390</date><user_ip>164.2.255.244</user_ip><user_agent>Mozilla/5.0 (Macintosh; U; PPC Mac OS X 10_4_11; fr) AppleWebKit/525.18 (KHTML, like Gecko) Version/3.1.1 Safari/525.18</user_agent><spam>0</spam></message><message mID="m54869f3098d4c29.79174517"><name>適当</name><website/><comment>どんな感じ？</comment><date>1214903049</date><user_ip>210.250.31.160</user_ip><user_agent>Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.0)</user_agent><spam>0</spam></message><message mID="m5486a0d6d6fdbb2.41524500"><name>sjaak</name><website/><comment>testing</comment><date>1214909805</date><user_ip>193.172.3.230</user_ip><user_agent>Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10.5; en-US; rv:1.9) Gecko/2008061004 Firefox/3.0</user_agent><spam>0</spam></message><message mID="m2486a1237435ec6.43329787"><name>ciastko</name><website>http://www.obrazy.ovh.org</website><comment>tset</comment><date>1214911031</date><user_ip>90.156.29.238</user_ip><user_agent>Opera/9.50 (Windows NT 5.1; U; pl)</user_agent><spam>0</spam></message><message mID="m1486a143be3c6d8.58653476"><name>Greg</name><website/><comment>Hello</comment><date>1214911547</date><user_ip>92.233.98.179</user_ip><user_agent>Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.0; SLCC1; .NET CLR 2.0.50727; Media Center PC 5.0; .NET CLR 3.0.04506; WWTClient2)</user_agent><spam>0</spam></message><message mID="m2486a157a5fb678.53107630"><name>revan</name><website/><comment>test</comment><date>1214911866</date><user_ip>93.131.40.89</user_ip><user_agent>Mozilla/5.0 (Windows; U; Windows NT 6.0; de; rv:1.9) Gecko/2008052906 Firefox/3.0</user_agent><spam>0</spam></message><message mID="m2486a1990c98362.37500049"><name>TaopaiC</name><website>http://pctao.org</website><comment>test here</comment><date>1214912912</date><user_ip>61.229.130.45</user_ip><user_agent>Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.9) Gecko/2008061015 Firefox/3.0</user_agent><spam>0</spam></message><message mID="m2486a1e7abd5516.86948953"><name>efzez</name><website>http://http:/:www.test.be</website><comment>fezf</comment><date>1214914170</date><user_ip>78.22.183.43</user_ip><user_agent>Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_5_2; nl-nl) AppleWebKit/525.13 (KHTML, like Gecko) Version/3.1 Safari/525.13</user_agent><spam>0</spam></message><message mID="m5486a1ea4d8a374.73553725"><name>test</name><website>http://www.test.com</website><comment>test</comment><date>1214914212</date><user_ip>203.109.125.170</user_ip><user_agent>Mozilla/5.0 (Windows; U; Windows NT 5.0; en-US; rv:1.8.1.14) Gecko/20080404 Firefox/2.0.0.14</user_agent><spam>0</spam></message><message mID="m3486a23ae849471.54098868"><name>asas</name><website/><comment>asasasas</comment><date>1214915502</date><user_ip>194.252.49.120</user_ip><user_agent>Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.0; SLCC1; .NET CLR 2.0.50727; .NET CLR 3.0.04506; InfoPath.1)</user_agent><spam>0</spam></message><message mID="m4486a2745aac3a9.19775898"><name>fucker</name><website/><comment>fucking shit</comment><date>1214916421</date><user_ip>189.60.152.41</user_ip><user_agent>Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.9) Gecko/2008052906 Firefox/3.0</user_agent><spam>0</spam></message><message mID="m2486a274e58ee80.39545508"><name>qwe</name><website/><comment>qwe</comment><date>1214916430</date><user_ip>194.185.249.130</user_ip><user_agent>Mozilla/5.0 (Windows; U; Windows NT 5.1; it; rv:1.8.1.14) Gecko/20080404 Firefox/2.0.0.14</user_agent><spam>0</spam></message><message mID="m2486a278f237083.95623670"><name>fucker</name><website/><comment>just checking for filters...</comment><date>1214916494</date><user_ip>189.60.152.41</user_ip><user_agent>Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.9) Gecko/2008052906 Firefox/3.0</user_agent><spam>0</spam></message><message mID="m2486a2910aef2b8.26081731"><name>ifohdesigns</name><website/><comment>yeah</comment><date>1214916880</date><user_ip>209.0.114.9</user_ip><user_agent>Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.9) Gecko/2008052906 Firefox/3.0</user_agent><spam>0</spam></message><message mID="m1486a29210ce146.22040658"><name>ifohdesigns</name><website/><comment>another test?</comment><date>1214916896</date><user_ip>209.0.114.9</user_ip><user_agent>Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.9) Gecko/2008052906 Firefox/3.0</user_agent><spam>0</spam></message><message mID="m5486a2937bd4b23.15666733"><name>ifohdesigns</name><website/><comment>and without JS enabled...</comment><date>1214916919</date><user_ip>209.0.114.9</user_ip><user_agent>Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.9) Gecko/2008052906 Firefox/3.0</user_agent><spam>0</spam></message><message mID="m2486a2b19b137d1.36599287"><name>nice</name><website>http://www.dirtplug.com</website><comment>that is nice</comment><date>1214917401</date><user_ip>99.251.102.123</user_ip><user_agent>Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.9) Gecko/2008052906 Firefox/3.0</user_agent><spam>0</spam></message><message mID="m4486a2e9a9c49e8.88464754"><name>Test</name><website>http://test.com</website><comment>Test</comment><date>1214918298</date><user_ip>83.128.35.133</user_ip><user_agent>Mozilla/5.0 (Windows; U; Windows NT 5.1; nl; rv:1.8.1.14) Gecko/20080404 Firefox/2.0.0.14</user_agent><spam>0</spam></message><message mID="m2486a33ab24b970.29389748"><name>asdf</name><website/><comment>asdf asdf</comment><date>1214919595</date><user_ip>128.104.41.162</user_ip><user_agent>Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.8.1.14) Gecko/20080404 Firefox/2.0.0.14</user_agent><spam>0</spam></message><message mID="m2486a3570384190.35463940"><name>teste</name><website/><comment>teste</comment><date>1214920047</date><user_ip>200.102.85.151</user_ip><user_agent>Mozilla/5.0 (X11; U; Linux i686; pt-BR; rv:1.9) Gecko/2008052912 Firefox/3.0</user_agent><spam>0</spam></message><message mID="m4486a366f2f55d8.31003539"><name>fasteddie</name><website>http://www.google.com</website><comment>testing, testing</comment><date>1214920303</date><user_ip>204.16.137.174</user_ip><user_agent>Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.9) Gecko/2008052906 Firefox/3.0</user_agent><spam>0</spam></message><message mID="m5486a369a63d7a2.26069295"><name>fdsafdsa</name><website>http://fsdfds.com</website><comment>fdsafdsafdsa</comment><date>1214920346</date><user_ip>222.70.11.13</user_ip><user_agent>Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 5.1;  Embedded Web Browser from: http://bsalsa.com/; .NET CLR 1.1.4322; .NET CLR 2.0.50727; MAXTHON 2.0)</user_agent><spam>0</spam></message><message mID="m4486a46842e3e48.86827092"><name>test</name><website/><comment>this is NOT a test!  oh wait, ya it is</comment><date>1214924420</date><user_ip>162.27.9.20</user_ip><user_agent>Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.9) Gecko/2008052906 Firefox/3.0</user_agent><spam>0</spam></message><message mID="m1486a487a850301.99125192"><name>орпро</name><website/><comment>пропропр</comment><date>1214924922</date><user_ip>77.241.45.98</user_ip><user_agent>Mozilla/5.0 (Windows; U; Windows NT 5.1; ru; rv:1.8.1.14) Gecko/20080404 AdCentriaIM/1.7 Firefox/2.0.0.14</user_agent><spam>0</spam></message><message mID="m5486adb5d697939.45846506"><name>craig</name><website/><comment>test</comment><date>1214962525</date><user_ip>24.56.27.151</user_ip><user_agent>Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.9) Gecko/2008052906 Firefox/2.0 MEGAUPLOAD 1.0</user_agent><spam>0</spam></message><message mID="m5486ae36f986879.94077162"><name>name</name><website>http://test.jp</website><comment>テスト</comment><date>1214964591</date><user_ip>202.26.243.1</user_ip><user_agent>Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1; .NET CLR 1.1.4322; .NET CLR 2.0.50727)</user_agent><spam>0</spam></message><message mID="m5486af289157003.00960602"><name>aa</name><website>http://fairyfish.net</website><comment>aaa</comment><date>1214968456</date><user_ip>220.231.202.113</user_ip><user_agent>Mozilla/5.0 (Windows; U; Windows NT 5.1; zh-CN; rv:1.8.1.14) Gecko/20080404 Firefox/2.0.0.14</user_agent><spam>0</spam></message><message mID="m5486afb3a644ef5.51316078"><name>dh</name><website>http://www.webworthy.ca</website><comment>Looks good</comment><date>1214970682</date><user_ip>24.226.105.19</user_ip><user_agent>Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.8.1.14) Gecko/20080404 Firefox/2.0.0.14</user_agent><spam>0</spam></message><message mID="m3486b09796771a0.04593913"><name>Anoop</name><website/><comment>Here goes the comment</comment><date>1214974329</date><user_ip>59.93.3.155</user_ip><user_agent>Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 5.1; .NET CLR 2.0.50727)</user_agent><spam>0</spam></message><message mID="m3486b0cdd1224d9.79707415"><name>furniture indonesia</name><website>http://www.furniture-indonesia.biz</website><comment>testing</comment><date>1214975196</date><user_ip>114.30.80.4</user_ip><user_agent>Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.8.1.15) Gecko/20080623 Firefox/2.0.0.15</user_agent><spam>0</spam></message><message mID="m4486b19c88a7e62.40563570"><name>hi</name><website>http://www.wewe.com</website><comment>erewr</comment><date>1214978504</date><user_ip>210.23.5.12</user_ip><user_agent>Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.8.1.14) Gecko/20080404 Firefox/2.0.0.14</user_agent><spam>0</spam></message><message mID="m3486b359c7677f8.58919540"><name>me</name><website/><comment>test</comment><date>1214985628</date><user_ip>81.51.219.205</user_ip><user_agent>Mozilla/5.0 (Windows; U; Windows NT 5.0; fr; rv:1.9) Gecko/2008052906 Firefox/3.0</user_agent><spam>0</spam></message><message mID="m4486b3a86bfd698.35679936"><name>pp</name><website/><comment>ppp</comment><date>1214986886</date><user_ip>59.178.53.254</user_ip><user_agent>Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.9) Gecko/2008052906 Firefox/3.0</user_agent><spam>0</spam></message><message mID="m1486b3a96b0dff4.51153684"><name>pp</name><website/><comment>ppp</comment><date>1214986902</date><user_ip>59.178.53.254</user_ip><user_agent>Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.9) Gecko/2008052906 Firefox/3.0</user_agent><spam>0</spam></message><message mID="m4486b3a9d13eb80.02768775"><name>ppp</name><website/><comment>pppppppp</comment><date>1214986909</date><user_ip>59.178.53.254</user_ip><user_agent>Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.9) Gecko/2008052906 Firefox/3.0</user_agent><spam>0</spam></message><message mID="m5486b3ddcebded1.42548747"><name>64e</name><website/><comment>てすとー</comment><date>1214987740</date><user_ip>43.244.22.97</user_ip><user_agent>Opera/9.50 (Windows NT 5.1; U; ja)</user_agent><spam>0</spam></message><message mID="m5486b3df3d2d704.97286778"><name>あいあいあいあい</name><website/><comment>とりのれしまはれりちとしまはれりのとちしりれのとちしはひ

としちはりれのまとしは</comment><date>1214987763</date><user_ip>43.244.22.97</user_ip><user_agent>Opera/9.50 (Windows NT 5.1; U; ja)</user_agent><spam>0</spam></message><message mID="m5486b423caedfd7.26343391"><name>volkan</name><website>http://www.volkansenturk.com</website><comment>deneme</comment><date>1214988860</date><user_ip>88.249.21.141</user_ip><user_agent>Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 5.1; SU 3.011; .NET CLR 2.0.50727; .NET CLR 3.0.04506.648; .NET CLR 3.5.21022)</user_agent><spam>0</spam></message><message mID="m3486b64ad6a8a76.74701013"><name>Pagination</name><website>http://www.is.required</website><comment>in this guestbook</comment><date>1214997677</date><user_ip>195.93.162.22</user_ip><user_agent>Mozilla/5.0 (Windows; U; Windows NT 6.0; pl; rv:1.9) Gecko/2008052906 Firefox/3.0</user_agent><spam>0</spam></message><message mID="m5486bb7d609fb92.89892048"><name>Lorem ipsum</name><website>http://lipsum.com</website><comment>Lorem ipsum dolor amet</comment><date>1215018965</date><user_ip>201.231.111.44</user_ip><user_agent>Mozilla/5.0 (Macintosh; U; Intel Mac OS X; en-US; rv:1.8.1.15) Gecko/20080623 Firefox/2.0.0.15</user_agent><spam>0</spam></message><message mID="m3486bb80f6427e9.28367935"><name>sdfsdfsdf</name><website/><comment>dfasdfasdf</comment><date>1215019023</date><user_ip>201.231.111.44</user_ip><user_agent>Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.9) Gecko/2008061015 Firefox/3.0</user_agent><spam>0</spam></message><message mID="m2486bb8e9ed8c59.06401400"><name>dsadas</name><website/><comment>dsadasdas</comment><date>1215019241</date><user_ip>91.135.11.13</user_ip><user_agent>Mozilla/5.0 (Windows; U; Windows NT 5.1; en-GB; rv:1.9) Gecko/2008052906 Firefox/3.0</user_agent><spam>0</spam></message><message mID="m4486bb8f6714753.07916842"><name>fadf</name><website/><comment>fas</comment><date>1215019254</date><user_ip>91.135.11.13</user_ip><user_agent>Mozilla/5.0 (Windows; U; Windows NT 5.1; en-GB; rv:1.9) Gecko/2008052906 Firefox/3.0</user_agent><spam>0</spam></message><message mID="m4486bbae63aa091.99417297"><name>Fabio</name><website/><comment>teste</comment><date>1215019750</date><user_ip>201.3.76.5</user_ip><user_agent>Mozilla/5.0 (X11; U; Linux i686; pt-BR; rv:1.8.1.6) Gecko/20071008 Ubuntu/7.10 (gutsy) Firefox/2.0.0.6</user_agent><spam>0</spam></message><message mID="m2486bbaff2ae2f9.75863800"><name>chen</name><website>http://www.www.www</website><comment>hi</comment><date>1215019775</date><user_ip>124.77.142.95</user_ip><user_agent>Mozilla/5.0 (Windows; U; Windows NT 5.1; zh-CN; rv:1.9) Gecko/2008052906 Firefox/3.0</user_agent><spam>0</spam></message><message mID="m3486bc49d783e12.03149235"><name>sdfdsffsdfsdf</name><website>http://www.sdsdf.com</website><comment>sdfsdfds</comment><date>1215022237</date><user_ip>91.123.232.34</user_ip><user_agent>Mozilla/5.0 (Macintosh; U; Intel Mac OS X; en-US; rv:1.8.1.14) Gecko/20080404 Firefox/2.0.0.14</user_agent><spam>0</spam></message><message mID="m1486bc4aec42600.66240426"><name>qwdqdqwd</name><website>http://wwww.xyz.com</website><comment>sdfsfsdfsdfsdfsdfsdf</comment><date>1215022254</date><user_ip>91.123.232.34</user_ip><user_agent>Mozilla/5.0 (Macintosh; U; Intel Mac OS X; en-US; rv:1.8.1.14) Gecko/20080404 Firefox/2.0.0.14</user_agent><spam>0</spam></message><message mID="m5486bd25f6af296.12358842"><name>Sahjin</name><website>http://www.avvstudios.com</website><comment>testing</comment><date>1215025759</date><user_ip>88.105.23.214</user_ip><user_agent>Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.9) Gecko/2008052906 Firefox/3.0</user_agent><spam>0</spam></message><message mID="m3486bd329bcf450.71894257"><name>ammon</name><website/><comment>hello world</comment><date>1215025961</date><user_ip>65.174.191.8</user_ip><user_agent>Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_5_4; en-us) AppleWebKit/526.11 (KHTML, like Gecko) NetNewsWire/3.1.7b2</user_agent><spam>0</spam></message><message mID="m1486bdc4ea964d8.43452296"><name>jake</name><website/><comment>Very nice! UTF-8 (i see korean). Lets Try Some Umlaute: ÄäÖöÜüß</comment><date>1215028302</date><user_ip>213.39.168.25</user_ip><user_agent>Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10.5; de-DE; rv:1.9) Gecko/2008061004 Firefox/3.0</user_agent><spam>0</spam></message><message mID="m5486bf1c016e491.59861929"><name>BS</name><website/><comment>Пробный</comment><date>1215033791</date><user_ip>88.87.80.6</user_ip><user_agent>Opera/9.23 (Windows NT 5.1; U; ru)</user_agent><spam>0</spam></message><message mID="m3486bf7870e8182.63210568"><name>johs</name><website>http://www.mush.com</website><comment>just a quick one</comment><date>1215035270</date><user_ip>79.77.62.12</user_ip><user_agent>Mozilla/5.0 (Macintosh; U; PPC Mac OS X Mach-O; en-US; rv:1.8.1.14) Gecko/20080404 Firefox/2.0.0.14</user_agent><spam>0</spam></message><message mID="m2486c1fce33de96.47468917"><name>mancio</name><website>http://cazzodecane.com.com</website><comment>bella zi</comment><date>1215045582</date><user_ip>85.18.140.196</user_ip><user_agent>Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 5.1; Alitalia Custom; Alitalia Custom; Alitalia Custom)</user_agent><spam>0</spam></message><message mID="m1486c270a09b841.66739468"><name>jjjj</name><website/><comment>jjj</comment><date>1215047433</date><user_ip>88.212.16.30</user_ip><user_agent>Opera/9.50 (Windows NT 5.1; U; cs)</user_agent><spam>0</spam></message><message mID="m1486c302c024e66.23770112"><name>pedro Taquelim</name><website/><comment>olá cabrões!</comment><date>1215049771</date><user_ip>77.54.108.63</user_ip><user_agent>Mozilla/5.0 (Macintosh; U; PPC Mac OS X 10_4_11; pt-pt) AppleWebKit/525.18 (KHTML, like Gecko) Version/3.1.2 Safari/525.22</user_agent><spam>0</spam></message><message mID="m1486c323e6ec266.44014589"><name>cioy</name><website>http://www.cioy.com</website><comment>sklj sdkljf klsdjf lsdkjf ldsf</comment><date>1215050302</date><user_ip>116.12.230.43</user_ip><user_agent>Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.8.1.14) Gecko/20080404 Firefox/2.0.0.14</user_agent><spam>0</spam></message><message mID="m5486c366b125867.24379561"><name>sdafasdfasdfasdfsdfdas</name><website/><comment>fsdfsdafsdfasdfasdfsdfasf</comment><date>1215051370</date><user_ip>202.146.241.5</user_ip><user_agent>Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 5.1)</user_agent><spam>0</spam></message><message mID="m5486c5f774503d6.47434366"><name>ostern58</name><website>http://www.beyourbest.de</website><comment>nice...</comment><date>1215061878</date><user_ip>84.142.227.19</user_ip><user_agent>Mozilla/5.0 (Windows; U; Windows NT 5.1; de; rv:1.9) Gecko/2008052906 Firefox/3.0</user_agent><spam>0</spam></message><message mID="m2486c60efc49754.46097969"><name>FHER</name><website>http://paganeo.com</website><comment>test</comment><date>1215062255</date><user_ip>190.212.15.68</user_ip><user_agent>Mozilla/5.0 (Windows; U; Windows NT 5.1; es-AR; rv:1.9) Gecko/2008052906 Firefox/3.0</user_agent><spam>0</spam></message><message mID="m1486c6b7a7ae0f4.42345646"><name>abc</name><website/><comment>test it</comment><date>1215064954</date><user_ip>216.224.242.122</user_ip><user_agent>Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.8.1.14) Gecko/20080404 Firefox/2.0.0.14</user_agent><spam>0</spam></message><message mID="m4486c79e261b1e8.82513300"><name>test</name><website>http://www.test.com</website><comment>test</comment><date>1215068642</date><user_ip>89.137.4.83</user_ip><user_agent>Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.8.1.15) Gecko/20080623 Firefox/2.0.0.15</user_agent><spam>0</spam></message><message mID="m2486c7b37695487.91956825"><name>pete</name><website/><comment>hi</comment><date>1215068983</date><user_ip>85.5.207.79</user_ip><user_agent>Mozilla/5.0 (Windows; U; Windows NT 6.0; fr; rv:1.9) Gecko/2008052906 Firefox/3.0</user_agent><spam>0</spam></message><message mID="m5486c7b38a97fa7.38208016"><name>waesrgdgbfh</name><website>http://www.outriggercanoe.de</website><comment>fsyvesydvse</comment><date>1215068984</date><user_ip>91.2.196.111</user_ip><user_agent>Mozilla/5.0 (Windows; U; Windows NT 5.1; de; rv:1.8.1.15) Gecko/20080623 Firefox/2.0.0.15</user_agent><spam>0</spam></message><message mID="m2486c7bf32dde04.46703259"><name>wtf!?</name><website>http://www.google.com</website><comment>hello?</comment><date>1215069171</date><user_ip>213.23.255.102</user_ip><user_agent>Mozilla/5.0 (Windows; U; Windows NT 6.0; de; rv:1.9) Gecko/2008052906 Firefox/3.0</user_agent><spam>0</spam></message><message mID="m3486c7c163f6c08.88472499"><name>YanK (Développeur web)</name><website>http://www.kermarec.com</website><comment>Petit test de JibberBook ;)</comment><date>1215069206</date><user_ip>88.168.136.80</user_ip><user_agent>Mozilla/5.0 (Windows; U; Windows NT 5.1; fr; rv:1.9) Gecko/2008052906 Firefox/3.0</user_agent><spam>0</spam></message><message mID="m2486c7c7dba72b1.58932457"><name>bvdbdfsgb</name><website/><comment>dbfx</comment><date>1215069309</date><user_ip>124.171.241.155</user_ip><user_agent>Mozilla/5.0 (Windows; U; Windows NT 6.0; en-US; rv:1.9) Gecko/2008052906 Firefox/3.0</user_agent><spam>0</spam></message><message mID="m3486c7c985fbcc1.73541449"><name>kjkj</name><website/><comment>mjh.lk</comment><date>1215069336</date><user_ip>92.72.9.170</user_ip><user_agent>Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_5_4; de-de) AppleWebKit/525.18 (KHTML, like Gecko) Version/3.1.2 Safari/525.20.1</user_agent><spam>0</spam></message><message mID="m4486c7ca32bd157.18168640"><name>me</name><website/><comment>nice</comment><date>1215069347</date><user_ip>78.98.100.15</user_ip><user_agent>Mozilla/5.0 (Windows; U; Windows NT 5.1; sk; rv:1.8.1.15) Gecko/20080623 Firefox/2.0.0.12;MEGAUPLOAD 1.0</user_agent><spam>0</spam></message><message mID="m2486c7d73597ca5.39516980"><name>g</name><website/><comment>thats a very lame comment</comment><date>1215069555</date><user_ip>131.152.89.45</user_ip><user_agent>Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 5.1; InfoPath.1; .NET CLR 1.1.4322; .NET CLR 2.0.50727; .NET CLR 3.0.04506.30)</user_agent><spam>0</spam></message><message mID="m5486c7d9809cd58.44933178"><name>Alpha</name><website>http://alphachoi.cn</website><comment>Alpha Blog</comment><date>1215069591</date><user_ip>218.19.72.82</user_ip><user_agent>Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 5.1; InfoPath.2; .NET CLR 2.0.50727; TheWorld)</user_agent><spam>0</spam></message><message mID="m5486c7ddb70bf80.38946091"><name>Chris</name><website>http://www.cjsdesign.nl</website><comment>Nice!!!</comment><date>1215069659</date><user_ip>86.87.177.96</user_ip><user_agent>Mozilla/5.0 (Windows; U; Windows NT 5.1; nl; rv:1.9) Gecko/2008052906 Firefox/3.0</user_agent><spam>0</spam></message><message mID="m4486c7e26753b85.13450500"><name>Volcano</name><website/><comment>Nice</comment><date>1215069734</date><user_ip>80.32.97.232</user_ip><user_agent>Mozilla/5.0 (Windows; U; Windows NT 5.1; es-ES; rv:1.8.1.15) Gecko/20080623 Firefox/2.0.0.15</user_agent><spam>0</spam></message><message mID="m4486c7e4566b3f8.05830150"><name>Comment</name><website>http://jibberbook.com/demo/</website><comment>Add Comment</comment><date>1215069765</date><user_ip>193.195.220.180</user_ip><user_agent>Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 5.1; .NET CLR 1.1.4322; .NET CLR 2.0.50727; .NET CLR 3.0.04506.30; .NET CLR 3.0.04506.648)</user_agent><spam>0</spam></message><message mID="m5486c7e6dd94ea0.42549190"><name>kkkkkkkkkkkkk</name><website/><comment>kkkkkkkkkkkkkk</comment><date>1215069805</date><user_ip>83.208.41.249</user_ip><user_agent>Opera/9.50 (Windows NT 6.0; U; cs)</user_agent><spam>0</spam></message><message mID="m2486c7ec8ddbfb9.00557955"><name>f</name><website>http://www.google.de</website><comment>f</comment><date>1215069896</date><user_ip>62.159.140.34</user_ip><user_agent>Mozilla/5.0 (Windows; U; Windows NT 5.1; de; rv:1.8.1.15) Gecko/20080623 Firefox/2.0.0.15</user_agent><spam>0</spam></message><message mID="m1486c7ecfeed337.89423944"><name>dfdfd</name><website/><comment>fdfdfd</comment><date>1215069903</date><user_ip>77.49.116.240</user_ip><user_agent>Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_5_3; el-gr) AppleWebKit/525.18 (KHTML, like Gecko) Version/3.1.1 Safari/525.20</user_agent><spam>0</spam></message><message mID="m2486c7ed8c26463.05730510"><name>fws</name><website>http://www.dr.com</website><comment>fsdsd</comment><date>1215069912</date><user_ip>87.78.176.149</user_ip><user_agent>Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 5.1)</user_agent><spam>0</spam></message><message mID="m5486c7ee0343635.74321105"><name>test</name><website>http://www.google.de</website><comment>asdfasdf</comment><date>1215069920</date><user_ip>217.91.79.130</user_ip><user_agent>Mozilla/5.0 (Windows; U; Windows NT 6.0; de; rv:1.9) Gecko/2008052906 Dealio Toolbar 3.3 Firefox/3.0</user_agent><spam>0</spam></message><message mID="m4486c7ef90575b9.32820784"><name>blubber</name><website/><comment>blubbbbb</comment><date>1215069944</date><user_ip>87.78.176.149</user_ip><user_agent>Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 5.1)</user_agent><spam>0</spam></message><message mID="m1486c7f8adf7990.10284763"><name>tesss</name><website/><comment>tttt</comment><date>1215070090</date><user_ip>62.156.141.116</user_ip><user_agent>Mozilla/5.0 (Windows; U; Windows NT 5.1; en-GB; rv:1.8.1.14) Gecko/20080404 Firefox/2.0.0.14</user_agent><spam>0</spam></message><message mID="m5486c7fd36f3208.04830980"><name>Administratorsdf</name><website>http://peterpan.ru</website><comment>sddsafsdaf</comment><date>1215070163</date><user_ip>212.203.86.82</user_ip><user_agent>Mozilla/5.0 (Windows; U; Windows NT 5.1; de; rv:1.9) Gecko/2008052906 Firefox/3.0</user_agent><spam>0</spam></message><message mID="m5486c8000211c74.13202044"><name>suckina</name><website>http://ruru.ru</website><comment>sddsafsdaf :) :)</comment><date>1215070208</date><user_ip>212.203.86.82</user_ip><user_agent>Mozilla/5.0 (Windows; U; Windows NT 5.1; de; rv:1.9) Gecko/2008052906 Firefox/3.0</user_agent><spam>0</spam></message><message mID="m5486c800cc7dba5.56643265"><name>aaa</name><website/><comment>fasfsdfasdf</comment><date>1215070220</date><user_ip>83.3.98.98</user_ip><user_agent>Mozilla/5.0 (Windows; U; Windows NT 6.0; pl; rv:1.9) Gecko/2008052906 Firefox/3.0</user_agent><spam>0</spam></message><message mID="m4486c8020d2d7f1.47057856"><name>saf</name><website/><comment>Twoja stara</comment><date>1215070240</date><user_ip>87.205.193.107</user_ip><user_agent>Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_5_4; pl-pl) AppleWebKit/525.18 (KHTML, like Gecko) NetNewsWire/3.1.7b2</user_agent><spam>0</spam></message><message mID="m3486c808da7d879.09162210"><name>dgj</name><website/><comment>jgfjd</comment><date>1215070349</date><user_ip>81.174.55.26</user_ip><user_agent>Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10.5; en-US; rv:1.9) Gecko/2008061004 Firefox/3.0</user_agent><spam>0</spam></message><message mID="m4486c81be3574a1.30793781"><name>fireyy</name><website>http://www.fireyy.com</website><comment>it&amp;#039;s cool!</comment><date>1215070654</date><user_ip>116.228.42.89</user_ip><user_agent>Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_5_4; zh-cn) AppleWebKit/525.18 (KHTML, like Gecko) Version/3.1.2 Safari/525.20.1</user_agent><spam>0</spam></message><message mID="m4486c81c62a6ef6.46686237"><name>gdgdfg</name><website/><comment>fgdfgfdg fg</comment><date>1215070662</date><user_ip>213.17.149.50</user_ip><user_agent>Mozilla/5.0 (Windows; U; Windows NT 6.0; pl; rv:1.9) Gecko/2008052906 googlebot</user_agent><spam>0</spam></message><message mID="m4486c8227eb46e7.28397288"><name>John</name><website>http://www.SimpleMinds.com</website><comment>This is a Nice Feature</comment><date>1215070759</date><user_ip>86.43.125.33</user_ip><user_agent>Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.9) Gecko/2008052906 Firefox/3.0</user_agent><spam>0</spam></message><message mID="m2486c82ed83cee6.13870989"><name>MonNom</name><website>http://aleph2at.free.fr</website><comment>Mon Commentaire</comment><date>1215070957</date><user_ip>86.65.191.54</user_ip><user_agent>Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1; .NET CLR 1.1.4322; InfoPath.1; .NET CLR 2.0.50727)</user_agent><spam>0</spam></message><message mID="m2486c8319c81a51.63521888"><name>rob</name><website/><comment>good</comment><date>1215071001</date><user_ip>83.103.40.171</user_ip><user_agent>Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_5_4; it-it) AppleWebKit/525.18 (KHTML, like Gecko) Version/3.1.2 Safari/525.20.1</user_agent><spam>0</spam></message><message mID="m3486c83a60dc237.51669374"><name>Leo</name><website/><comment>Ciao</comment><date>1215071141</date><user_ip>82.107.117.141</user_ip><user_agent>Mozilla/5.0 (Windows; U; Windows NT 6.0; it; rv:1.9) Gecko/2008052906 Firefox/3.0</user_agent><spam>0</spam></message><message mID="m1486c83c1288cd9.34738205"><name>dsfs</name><website/><comment>sfdfd f</comment><date>1215071169</date><user_ip>213.255.101.170</user_ip><user_agent>Mozilla/5.0 (Windows; U; Windows NT 5.1; it; rv:1.9) Gecko/2008052906 Firefox/3.0</user_agent><spam>0</spam></message><message mID="m4486c83e1a591a5.31245535"><name>11</name><website/><comment>11111</comment><date>1215071201</date><user_ip>61.218.68.230</user_ip><user_agent>Mozilla/5.0 (Windows; U; Windows NT 5.1; zh-TW; rv:1.9) Gecko/2008052906 Firefox/3.0</user_agent><spam>0</spam></message><message mID="m5486c842ea31bb2.22759517"><name>The Horst</name><website>http://www.abc.com</website><comment>test test test</comment><date>1215071278</date><user_ip>134.1.4.98</user_ip><user_agent>Mozilla/5.0 (Windows; U; Windows NT 5.1; de; rv:1.9) Gecko/2008052906 Firefox/3.0</user_agent><spam>0</spam></message><message mID="m1486c845e701573.63654168"><name>jim</name><website/><comment>oooooooooooooooooooooooooooooooo</comment><date>1215071326</date><user_ip>92.43.64.74</user_ip><user_agent>Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.8.1.2) Gecko/20070219 Firefox/2.0.0.2</user_agent><spam>0</spam></message><message mID="m4486c846e04baf4.14300659"><name>te</name><website/><comment>te</comment><date>1215071341</date><user_ip>89.171.67.2</user_ip><user_agent>Mozilla/5.0 (Windows; U; Windows NT 5.1; pl; rv:1.9) Gecko/2008052906 Firefox/3.0</user_agent><spam>0</spam></message><message mID="m4486c84c316da67.2